parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 8888
    database_name: todolist
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: c4b9c32e0565710db1f0f07f7b54be15f3674d4f
    database_path: null
