parameters:
#    keynetic_blog.example.class: Keynetic\BlogBundle\Example

services:
#    keynetic_blog.example:
#        class: %keynetic_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
