keynetic_to_do_list_homepage:
    pattern:  /
    defaults: { _controller: KeyneticToDoListBundle:ToDoList:index }

keynetic_to_do_list_homepage_index:
    pattern:  /index
    defaults: { _controller: KeyneticToDoListBundle:ToDoList:index }

accueil:
    pattern:  /accueil
    defaults: { _controller: KeyneticToDoListBundle:ToDoList:index }

accueil_post:
    pattern:  /accueil/{id}
    defaults: { _controller: KeyneticToDoListBundle:ToDoList:index }
    requirements:
        id: \d+
        
modifier:
    pattern:  /modifier/{id}
    defaults: { _controller: KeyneticToDoListBundle:ToDoList:modifier }
    requirements:
        id: \d+